# Generated by Django 3.1.5 on 2021-01-24 07:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Objects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comName', models.CharField(blank=True, max_length=36, null=True)),
                ('category', models.CharField(blank=True, max_length=20, null=True)),
                ('partNum', models.CharField(blank=True, max_length=20, null=True)),
                ('supplier', models.CharField(blank=True, max_length=20, null=True)),
                ('uom', models.CharField(blank=True, max_length=20, null=True)),
                ('image', models.ImageField(blank=True, upload_to='tec-spec')),
                ('drawing', models.CharField(blank=True, max_length=20, null=True)),
                ('weight', models.CharField(blank=True, max_length=20, null=True)),
                ('dtCreate', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'objects',
            },
        ),
    ]
